//! Typed three-digit numeric replies.
//!
//! Every code listed here is an RFC 2812 or IRCv3 reply the server or
//! client is expected to recognise. Unlisted codes fall through to
//! [`ReplyCode::Unknown`] so forward-compatibility with vendor
//! extensions is automatic.
//!
//! The enum is a flat lookup table generated by the `replycode!` macro.
//! It lives in this crate because both the server (emits) and the
//! client (dispatches) need the same taxonomy.

macro_rules! replycode {
    ( $($(#[$m:meta])* $variant:ident = $code:literal),* $(,)? ) => {
        /// Named three-digit reply codes used by the server and client.
        ///
        /// Only the codes we know how to produce or dispatch are
        /// listed; everything else surfaces as [`ReplyCode::Unknown`].
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[non_exhaustive]
        #[allow(missing_docs, non_camel_case_types)] // RFC-named variants kept SCREAMING_SNAKE_CASE for searchability
        pub enum ReplyCode {
            $( $(#[$m])* $variant, )*
            /// Any three-digit code not enumerated above. Preserved so
            /// vendor extensions round-trip without loss.
            Unknown(u16),
        }

        impl ReplyCode {
            /// Three-digit numeric code on the wire.
            #[must_use]
            pub const fn code(self) -> u16 {
                match self {
                    $( Self::$variant => $code, )*
                    Self::Unknown(c) => c,
                }
            }

            /// Canonical symbolic name (`RPL_WELCOME`, `ERR_NICKNAMEINUSE`, …).
            /// Returns `"UNKNOWN"` for [`ReplyCode::Unknown`].
            #[must_use]
            pub const fn name(self) -> &'static str {
                match self {
                    $( Self::$variant => stringify!($variant), )*
                    Self::Unknown(_) => "UNKNOWN",
                }
            }
        }

        impl From<u16> for ReplyCode {
            fn from(code: u16) -> Self {
                match code {
                    $( $code => Self::$variant, )*
                    other => Self::Unknown(other),
                }
            }
        }

        impl From<ReplyCode> for u16 {
            fn from(rc: ReplyCode) -> Self { rc.code() }
        }
    };
}

replycode! {
    // Connection / registration
    // --- Connection / registration ---
    RPL_WELCOME = 1,
    RPL_YOURHOST = 2,
    RPL_CREATED = 3,
    RPL_MYINFO = 4,
    RPL_ISUPPORT = 5,

    // --- LUSERS ---
    RPL_LUSERCLIENT = 251,
    RPL_LUSEROP = 252,
    RPL_LUSERUNKNOWN = 253,
    RPL_LUSERCHANNELS = 254,
    RPL_LUSERME = 255,

    // --- AWAY / messaging side band ---
    RPL_AWAY = 301,
    RPL_UNAWAY = 305,
    RPL_NOWAWAY = 306,

    // --- WHOIS / WHOWAS / WHO ---
    RPL_WHOISUSER = 311,
    RPL_WHOISSERVER = 312,
    RPL_WHOISOPERATOR = 313,
    RPL_WHOWASUSER = 314,
    RPL_ENDOFWHO = 315,
    RPL_WHOISIDLE = 317,
    RPL_ENDOFWHOIS = 318,
    RPL_WHOISCHANNELS = 319,

    // --- LIST ---
    RPL_LIST = 322,
    RPL_LISTEND = 323,

    // --- Channel topic / names ---
    RPL_CHANNELMODEIS = 324,
    RPL_NOTOPIC = 331,
    RPL_TOPIC = 332,
    RPL_TOPICWHOTIME = 333,

    // --- INVITE / WHO reply ---
    RPL_INVITING = 341,
    RPL_WHOREPLY = 352,
    RPL_NAMREPLY = 353,
    RPL_ENDOFNAMES = 366,

    // --- WHOWAS / account ---
    RPL_ENDOFWHOWAS = 369,
    RPL_WHOISACCOUNT = 330,

    // --- MOTD ---
    RPL_MOTD = 372,
    RPL_MOTDSTART = 375,
    RPL_ENDOFMOTD = 376,

    // --- Oper ---
    RPL_YOUREOPER = 381,

    // --- Channel info ---
    RPL_BANLIST = 367,
    RPL_ENDOFBANLIST = 368,

    // --- Errors (400s) ---
    ERR_NOSUCHNICK = 401,
    ERR_NOSUCHSERVER = 402,
    ERR_NOSUCHCHANNEL = 403,
    ERR_CANNOTSENDTOCHAN = 404,
    ERR_TOOMANYCHANNELS = 405,
    ERR_UNKNOWNCOMMAND = 421,
    ERR_NOMOTD = 422,
    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,
    ERR_USERNOTINCHANNEL = 441,
    ERR_NOTONCHANNEL = 442,
    ERR_USERONCHANNEL = 443,
    ERR_NOTREGISTERED = 451,
    ERR_NEEDMOREPARAMS = 461,
    ERR_ALREADYREGISTERED = 462,
    ERR_PASSWDMISMATCH = 464,
    ERR_YOUREBANNEDCREEP = 465,
    ERR_CHANNELISFULL = 471,
    ERR_UNKNOWNMODE = 472,
    ERR_INVITEONLYCHAN = 473,
    ERR_BANNEDFROMCHAN = 474,
    ERR_BADCHANNELKEY = 475,
    ERR_NOPRIVILEGES = 481,
    ERR_CHANOPRIVSNEEDED = 482,
    ERR_CANTKILLSERVER = 483,
    ERR_NOOPERHOST = 491,
    ERR_UMODEUNKNOWNFLAG = 501,
    ERR_USERSDONTMATCH = 502,

    // --- CAP ---
    ERR_INVALIDCAPCMD = 410,

    // --- SASL (IRCv3) ---
    RPL_LOGGEDIN = 900,
    RPL_LOGGEDOUT = 901,
    ERR_NICKLOCKED = 902,
    RPL_SASLSUCCESS = 903,
    ERR_SASLFAIL = 904,
    ERR_SASLTOOLONG = 905,
    ERR_SASLABORTED = 906,
    ERR_SASLALREADY = 907,
    RPL_SASLMECHS = 908,

    // --- Account registration (custom) ---
    RPL_REG_VERIFICATION_REQUIRED = 920,
    RPL_REG_SUCCESS = 921,
    ERR_REG_INVALID = 922,
    ERR_REG_ALREADY_EXISTS = 923,

    // --- MONITOR (IRCv3) ---
    RPL_MONONLINE = 730,
    RPL_MONOFFLINE = 731,
    RPL_MONLIST = 732,
    RPL_ENDOFMONLIST = 733,
    ERR_MONLISTFULL = 734,
}

impl ReplyCode {
    /// `true` when this code is an error reply (400-599 range) or a
    /// named `ERR_*`.
    #[must_use]
    pub const fn is_error(self) -> bool {
        let c = self.code();
        c >= 400 && c < 600
    }
}

#[cfg(test)]
mod tests {
    use super::ReplyCode;

    #[test]
    fn welcome_code_is_one() {
        assert_eq!(ReplyCode::RPL_WELCOME.code(), 1);
        assert_eq!(u16::from(ReplyCode::RPL_WELCOME), 1);
        assert_eq!(ReplyCode::from(1), ReplyCode::RPL_WELCOME);
    }

    #[test]
    fn nickname_in_use_is_error() {
        let rc = ReplyCode::from(433);
        assert_eq!(rc, ReplyCode::ERR_NICKNAMEINUSE);
        assert!(rc.is_error());
        assert_eq!(rc.name(), "ERR_NICKNAMEINUSE");
    }

    #[test]
    fn sasl_success_surfaces_as_name() {
        assert_eq!(ReplyCode::RPL_SASLSUCCESS.name(), "RPL_SASLSUCCESS");
        assert_eq!(ReplyCode::RPL_SASLSUCCESS.code(), 903);
    }

    #[test]
    fn unknown_code_round_trips() {
        let rc = ReplyCode::from(777);
        assert_eq!(rc, ReplyCode::Unknown(777));
        assert_eq!(rc.code(), 777);
        assert_eq!(rc.name(), "UNKNOWN");
    }

    #[test]
    fn is_error_boundaries() {
        assert!(!ReplyCode::from(399).is_error());
        assert!(ReplyCode::from(400).is_error());
        assert!(ReplyCode::from(599).is_error());
        assert!(!ReplyCode::from(600).is_error());
    }
}
