// This would normally be generated by diesel_cli, but since we're not installing it,
// we write it manually to match our migrations.

diesel::table! {
    users (id) {
        id -> Uuid,
        username -> Varchar,
        password_hash -> Varchar,
        role -> Varchar,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    printers (id) {
        id -> Varchar,
        name -> Varchar,
        ip -> Varchar,
        serial -> Varchar,
        access_code -> Varchar,
        model -> Varchar,
        owner_id -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    print_jobs (id) {
        id -> Uuid,
        printer_id -> Varchar,
        file_name -> Varchar,
        started_at -> Timestamptz,
        finished_at -> Nullable<Timestamptz>,
        status -> Varchar,
        total_layers -> Integer,
        duration_seconds -> Nullable<Integer>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    print_queue (id) {
        id -> Uuid,
        printer_id -> Varchar,
        file_name -> Varchar,
        plate_number -> Integer,
        status -> Varchar,
        position -> Integer,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    filament_usage (id) {
        id -> Uuid,
        print_job_id -> Nullable<Uuid>,
        printer_id -> Varchar,
        filament_type -> Varchar,
        color -> Varchar,
        weight_grams -> Nullable<Float>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    printer_assignments (id) {
        id -> Uuid,
        user_id -> Uuid,
        printer_id -> Varchar,
        created_at -> Timestamptz,
    }
}

diesel::joinable!(printers -> users (owner_id));
diesel::joinable!(print_jobs -> printers (printer_id));
diesel::joinable!(print_queue -> printers (printer_id));
diesel::joinable!(printer_assignments -> users (user_id));
diesel::joinable!(printer_assignments -> printers (printer_id));
diesel::allow_tables_to_appear_in_same_query!(users, printers, print_jobs, print_queue, filament_usage, printer_assignments);
