export enum LogsType {
    BUY = "BUY",
    SELL = "SELL",
    PUMPFUN_TOKEN_CREATION = "PUMPFUN_TOKEN_CREATION",
    PUMPFUN_RAYDIUM_MIGRATION = "PUMPFUN_RAYDIUM_MIGRATION",
    SPL_TOKEN_CREATION = "SPL_TOKEN_CREATION",
    IMAGE = "IMAGE"
}