[package]
name = "vm-data"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv.workspace = true
serde.workspace = true
serde_json.workspace = true

diesel.workspace = true
diesel-async.workspace = true
diesel_migrations.workspace = true
deadpool = { version = "0.12", features = ["rt_tokio_1"] }

bigdecimal.workspace = true
uuid.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest.workspace = true
rand.workspace = true

jsonwebtoken.workspace = true
ring.workspace = true
hex.workspace = true
once_cell.workspace = true
